version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: dnd-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: dnd_simulator
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - dnd-network

  app:
    build: .
    container_name: dnd-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      MONGO_URI: mongodb://admin:password123@mongodb:27017/dnd_simulator?authSource=admin
      DATABASE_NAME: dnd_simulator
      JWT_SECRET: super-secret-jwt-key-change-in-production
      GIN_MODE: release
    depends_on:
      - mongodb
    networks:
      - dnd-network

  # Optional: MongoDB Web UI
  mongo-express:
    image: mongo-express:1.0.0
    container_name: dnd-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - dnd-network
    profiles:
      - tools

volumes:
  mongodb_data:
    driver: local

networks:
  dnd-network:
    driver: bridge